/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.simiacryptus.api.java.openai;

import com.fasterxml.jackson.core.type.TypeReference;

import com.simiacryptus.api.java.ApiException;
import com.simiacryptus.api.java.ApiClient;
import com.simiacryptus.api.java.Configuration;
import com.simiacryptus.api.java.Pair;

import com.simiacryptus.api.java.openai.model.CreateEmbeddingRequest;
import com.simiacryptus.api.java.openai.model.CreateEmbeddingResponse;


import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-09T16:24:46.732753800-05:00[America/New_York]")
public class EmbeddingsApi {


  private ApiClient apiClient;

  public EmbeddingsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EmbeddingsApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Creates an embedding vector representing the input text.
   * 
   * @param createEmbeddingRequest  (required)
   * @return CreateEmbeddingResponse
   * @throws ApiException if fails to make API call
   */
  public CreateEmbeddingResponse createEmbedding(CreateEmbeddingRequest createEmbeddingRequest) throws ApiException {
    return this.createEmbedding(createEmbeddingRequest, Collections.emptyMap());
  }


  /**
   * Creates an embedding vector representing the input text.
   * 
   * @param createEmbeddingRequest  (required)
   * @param additionalHeaders additionalHeaders for this call
   * @return CreateEmbeddingResponse
   * @throws ApiException if fails to make API call
   */
  public CreateEmbeddingResponse createEmbedding(CreateEmbeddingRequest createEmbeddingRequest, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = createEmbeddingRequest;
    
    // verify the required parameter 'createEmbeddingRequest' is set
    if (createEmbeddingRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createEmbeddingRequest' when calling createEmbedding");
    }
    
    // create path and map variables
    String localVarPath = "/embeddings";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    
    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "ApiKeyAuth" };

    TypeReference<CreateEmbeddingResponse> localVarReturnType = new TypeReference<CreateEmbeddingResponse>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

}
