/*
 * ModelsLab AI API's
 * This is ModelsLab Stable Diffusion and Multiple AI APIs, here you can pass details to generate images using API, without needs of GPU locally.  You will need to have _**api key**_ to generate images, if you don't have it, get it from [https://modelslab.com](https://modelslab.com/)  Send Json post request with data and links, don't send files as raw format, send accessible links instead
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.modelslab.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for SystemDetails200Response
 */
public class SystemDetails200ResponseTest {
    private final SystemDetails200Response model = new SystemDetails200Response();

    /**
     * Model tests for SystemDetails200Response
     */
    @Test
    public void testSystemDetails200Response() {
        // TODO: test SystemDetails200Response
    }

    /**
     * Test the property 'modelCount'
     */
    @Test
    public void modelCountTest() {
        // TODO: test modelCount
    }

    /**
     * Test the property 'queueTime'
     */
    @Test
    public void queueTimeTest() {
        // TODO: test queueTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
