/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai;

import com.simiacryptus.api.java.ApiException;
import java.math.BigDecimal;
import com.simiacryptus.api.java.openai.model.CreateSpeechRequest;
import com.simiacryptus.api.java.openai.model.CreateTranscription200Response;
import com.simiacryptus.api.java.openai.model.CreateTranscriptionRequestModel;
import com.simiacryptus.api.java.openai.model.CreateTranslation200Response;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AudioApi
 */
@Ignore
public class AudioApiTest {

    private final AudioApi api = new AudioApi();

    /**
     * Generates audio from the input text.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSpeechTest() throws ApiException {
        CreateSpeechRequest createSpeechRequest = null;
        File response = api.createSpeech(createSpeechRequest);

        // TODO: test validations
    }
    /**
     * Transcribes audio into the input language.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTranscriptionTest() throws ApiException {
        File _file = null;
        CreateTranscriptionRequestModel model = null;
        String language = null;
        String prompt = null;
        String responseFormat = null;
        BigDecimal temperature = null;
        List<String> timestampGranularities = null;
        CreateTranscription200Response response = api.createTranscription(_file, model, language, prompt, responseFormat, temperature, timestampGranularities);

        // TODO: test validations
    }
    /**
     * Translates audio into English.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTranslationTest() throws ApiException {
        File _file = null;
        CreateTranscriptionRequestModel model = null;
        String prompt = null;
        String responseFormat = null;
        BigDecimal temperature = null;
        CreateTranslation200Response response = api.createTranslation(_file, model, prompt, responseFormat, temperature);

        // TODO: test validations
    }
}
