/*
 * ModelsLab AI API's
 * This is ModelsLab Stable Diffusion and Multiple AI APIs, here you can pass details to generate images using API, without needs of GPU locally.  You will need to have _**api key**_ to generate images, if you don't have it, get it from [https://modelslab.com](https://modelslab.com/)  Send Json post request with data and links, don't send files as raw format, send accessible links instead
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.modelslab.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * DreamboothInpaintingRequest
 */
@JsonPropertyOrder({
  DreamboothInpaintingRequest.JSON_PROPERTY_EMBEDDINGS_MODEL,
  DreamboothInpaintingRequest.JSON_PROPERTY_ENHANCE_PROMPT,
  DreamboothInpaintingRequest.JSON_PROPERTY_GUIDANCE_SCALE,
  DreamboothInpaintingRequest.JSON_PROPERTY_HEIGHT,
  DreamboothInpaintingRequest.JSON_PROPERTY_INIT_IMAGE,
  DreamboothInpaintingRequest.JSON_PROPERTY_KEY,
  DreamboothInpaintingRequest.JSON_PROPERTY_LORA_MODEL,
  DreamboothInpaintingRequest.JSON_PROPERTY_LORA_STRENGTH,
  DreamboothInpaintingRequest.JSON_PROPERTY_MASK_IMAGE,
  DreamboothInpaintingRequest.JSON_PROPERTY_MODEL_ID,
  DreamboothInpaintingRequest.JSON_PROPERTY_NEGATIVE_PROMPT,
  DreamboothInpaintingRequest.JSON_PROPERTY_NUM_INFERENCE_STEPS,
  DreamboothInpaintingRequest.JSON_PROPERTY_PROMPT,
  DreamboothInpaintingRequest.JSON_PROPERTY_SAFETY_CHECKER,
  DreamboothInpaintingRequest.JSON_PROPERTY_SAMPLES,
  DreamboothInpaintingRequest.JSON_PROPERTY_SCHEDULER,
  DreamboothInpaintingRequest.JSON_PROPERTY_SEED,
  DreamboothInpaintingRequest.JSON_PROPERTY_STRENGTH,
  DreamboothInpaintingRequest.JSON_PROPERTY_TOMESD,
  DreamboothInpaintingRequest.JSON_PROPERTY_TRACK_ID,
  DreamboothInpaintingRequest.JSON_PROPERTY_USE_KARRAS_SIGMAS,
  DreamboothInpaintingRequest.JSON_PROPERTY_VAE,
  DreamboothInpaintingRequest.JSON_PROPERTY_WEBHOOK,
  DreamboothInpaintingRequest.JSON_PROPERTY_WIDTH
})
@JsonTypeName("dreamboothInpainting_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-09T16:25:01.849546200-05:00[America/New_York]")
public class DreamboothInpaintingRequest {
  public static final String JSON_PROPERTY_EMBEDDINGS_MODEL = "embeddings_model";
  private JsonNullable<Object> embeddingsModel = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_ENHANCE_PROMPT = "enhance_prompt";
  private String enhancePrompt;

  public static final String JSON_PROPERTY_GUIDANCE_SCALE = "guidance_scale";
  private BigDecimal guidanceScale;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private String height;

  public static final String JSON_PROPERTY_INIT_IMAGE = "init_image";
  private String initImage;

  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_LORA_MODEL = "lora_model";
  private JsonNullable<Object> loraModel = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_LORA_STRENGTH = "lora_strength";
  private JsonNullable<Object> loraStrength = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_MASK_IMAGE = "mask_image";
  private String maskImage;

  public static final String JSON_PROPERTY_MODEL_ID = "model_id";
  private String modelId;

  public static final String JSON_PROPERTY_NEGATIVE_PROMPT = "negative_prompt";
  private JsonNullable<Object> negativePrompt = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_NUM_INFERENCE_STEPS = "num_inference_steps";
  private String numInferenceSteps;

  public static final String JSON_PROPERTY_PROMPT = "prompt";
  private String prompt;

  public static final String JSON_PROPERTY_SAFETY_CHECKER = "safety_checker";
  private String safetyChecker;

  public static final String JSON_PROPERTY_SAMPLES = "samples";
  private String samples;

  public static final String JSON_PROPERTY_SCHEDULER = "scheduler";
  private JsonNullable<Object> scheduler = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_SEED = "seed";
  private JsonNullable<Object> seed = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_STRENGTH = "strength";
  private BigDecimal strength;

  public static final String JSON_PROPERTY_TOMESD = "tomesd";
  private String tomesd;

  public static final String JSON_PROPERTY_TRACK_ID = "track_id";
  private JsonNullable<Object> trackId = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_USE_KARRAS_SIGMAS = "use_karras_sigmas";
  private String useKarrasSigmas;

  public static final String JSON_PROPERTY_VAE = "vae";
  private JsonNullable<Object> vae = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_WEBHOOK = "webhook";
  private JsonNullable<Object> webhook = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_WIDTH = "width";
  private String width;

  public DreamboothInpaintingRequest() {
  }

  public DreamboothInpaintingRequest embeddingsModel(Object embeddingsModel) {
    this.embeddingsModel = JsonNullable.<Object>of(embeddingsModel);
    
    return this;
  }

   /**
   * Get embeddingsModel
   * @return embeddingsModel
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getEmbeddingsModel() {
        return embeddingsModel.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EMBEDDINGS_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getEmbeddingsModel_JsonNullable() {
    return embeddingsModel;
  }
  
  @JsonProperty(JSON_PROPERTY_EMBEDDINGS_MODEL)
  public void setEmbeddingsModel_JsonNullable(JsonNullable<Object> embeddingsModel) {
    this.embeddingsModel = embeddingsModel;
  }

  public void setEmbeddingsModel(Object embeddingsModel) {
    this.embeddingsModel = JsonNullable.<Object>of(embeddingsModel);
  }


  public DreamboothInpaintingRequest enhancePrompt(String enhancePrompt) {
    
    this.enhancePrompt = enhancePrompt;
    return this;
  }

   /**
   * Get enhancePrompt
   * @return enhancePrompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENHANCE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnhancePrompt() {
    return enhancePrompt;
  }


  @JsonProperty(JSON_PROPERTY_ENHANCE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnhancePrompt(String enhancePrompt) {
    this.enhancePrompt = enhancePrompt;
  }


  public DreamboothInpaintingRequest guidanceScale(BigDecimal guidanceScale) {
    
    this.guidanceScale = guidanceScale;
    return this;
  }

   /**
   * Get guidanceScale
   * @return guidanceScale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GUIDANCE_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getGuidanceScale() {
    return guidanceScale;
  }


  @JsonProperty(JSON_PROPERTY_GUIDANCE_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuidanceScale(BigDecimal guidanceScale) {
    this.guidanceScale = guidanceScale;
  }


  public DreamboothInpaintingRequest height(String height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(String height) {
    this.height = height;
  }


  public DreamboothInpaintingRequest initImage(String initImage) {
    
    this.initImage = initImage;
    return this;
  }

   /**
   * Get initImage
   * @return initImage
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INIT_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInitImage() {
    return initImage;
  }


  @JsonProperty(JSON_PROPERTY_INIT_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInitImage(String initImage) {
    this.initImage = initImage;
  }


  public DreamboothInpaintingRequest key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(String key) {
    this.key = key;
  }


  public DreamboothInpaintingRequest loraModel(Object loraModel) {
    this.loraModel = JsonNullable.<Object>of(loraModel);
    
    return this;
  }

   /**
   * Get loraModel
   * @return loraModel
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getLoraModel() {
        return loraModel.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LORA_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getLoraModel_JsonNullable() {
    return loraModel;
  }
  
  @JsonProperty(JSON_PROPERTY_LORA_MODEL)
  public void setLoraModel_JsonNullable(JsonNullable<Object> loraModel) {
    this.loraModel = loraModel;
  }

  public void setLoraModel(Object loraModel) {
    this.loraModel = JsonNullable.<Object>of(loraModel);
  }


  public DreamboothInpaintingRequest loraStrength(Object loraStrength) {
    this.loraStrength = JsonNullable.<Object>of(loraStrength);
    
    return this;
  }

   /**
   * Get loraStrength
   * @return loraStrength
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getLoraStrength() {
        return loraStrength.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LORA_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getLoraStrength_JsonNullable() {
    return loraStrength;
  }
  
  @JsonProperty(JSON_PROPERTY_LORA_STRENGTH)
  public void setLoraStrength_JsonNullable(JsonNullable<Object> loraStrength) {
    this.loraStrength = loraStrength;
  }

  public void setLoraStrength(Object loraStrength) {
    this.loraStrength = JsonNullable.<Object>of(loraStrength);
  }


  public DreamboothInpaintingRequest maskImage(String maskImage) {
    
    this.maskImage = maskImage;
    return this;
  }

   /**
   * Get maskImage
   * @return maskImage
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASK_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMaskImage() {
    return maskImage;
  }


  @JsonProperty(JSON_PROPERTY_MASK_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaskImage(String maskImage) {
    this.maskImage = maskImage;
  }


  public DreamboothInpaintingRequest modelId(String modelId) {
    
    this.modelId = modelId;
    return this;
  }

   /**
   * Get modelId
   * @return modelId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModelId() {
    return modelId;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelId(String modelId) {
    this.modelId = modelId;
  }


  public DreamboothInpaintingRequest negativePrompt(Object negativePrompt) {
    this.negativePrompt = JsonNullable.<Object>of(negativePrompt);
    
    return this;
  }

   /**
   * Get negativePrompt
   * @return negativePrompt
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getNegativePrompt() {
        return negativePrompt.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getNegativePrompt_JsonNullable() {
    return negativePrompt;
  }
  
  @JsonProperty(JSON_PROPERTY_NEGATIVE_PROMPT)
  public void setNegativePrompt_JsonNullable(JsonNullable<Object> negativePrompt) {
    this.negativePrompt = negativePrompt;
  }

  public void setNegativePrompt(Object negativePrompt) {
    this.negativePrompt = JsonNullable.<Object>of(negativePrompt);
  }


  public DreamboothInpaintingRequest numInferenceSteps(String numInferenceSteps) {
    
    this.numInferenceSteps = numInferenceSteps;
    return this;
  }

   /**
   * Get numInferenceSteps
   * @return numInferenceSteps
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUM_INFERENCE_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumInferenceSteps() {
    return numInferenceSteps;
  }


  @JsonProperty(JSON_PROPERTY_NUM_INFERENCE_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumInferenceSteps(String numInferenceSteps) {
    this.numInferenceSteps = numInferenceSteps;
  }


  public DreamboothInpaintingRequest prompt(String prompt) {
    
    this.prompt = prompt;
    return this;
  }

   /**
   * Get prompt
   * @return prompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrompt() {
    return prompt;
  }


  @JsonProperty(JSON_PROPERTY_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrompt(String prompt) {
    this.prompt = prompt;
  }


  public DreamboothInpaintingRequest safetyChecker(String safetyChecker) {
    
    this.safetyChecker = safetyChecker;
    return this;
  }

   /**
   * Get safetyChecker
   * @return safetyChecker
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAFETY_CHECKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSafetyChecker() {
    return safetyChecker;
  }


  @JsonProperty(JSON_PROPERTY_SAFETY_CHECKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSafetyChecker(String safetyChecker) {
    this.safetyChecker = safetyChecker;
  }


  public DreamboothInpaintingRequest samples(String samples) {
    
    this.samples = samples;
    return this;
  }

   /**
   * Get samples
   * @return samples
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSamples() {
    return samples;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSamples(String samples) {
    this.samples = samples;
  }


  public DreamboothInpaintingRequest scheduler(Object scheduler) {
    this.scheduler = JsonNullable.<Object>of(scheduler);
    
    return this;
  }

   /**
   * Get scheduler
   * @return scheduler
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getScheduler() {
        return scheduler.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCHEDULER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getScheduler_JsonNullable() {
    return scheduler;
  }
  
  @JsonProperty(JSON_PROPERTY_SCHEDULER)
  public void setScheduler_JsonNullable(JsonNullable<Object> scheduler) {
    this.scheduler = scheduler;
  }

  public void setScheduler(Object scheduler) {
    this.scheduler = JsonNullable.<Object>of(scheduler);
  }


  public DreamboothInpaintingRequest seed(Object seed) {
    this.seed = JsonNullable.<Object>of(seed);
    
    return this;
  }

   /**
   * Get seed
   * @return seed
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getSeed() {
        return seed.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getSeed_JsonNullable() {
    return seed;
  }
  
  @JsonProperty(JSON_PROPERTY_SEED)
  public void setSeed_JsonNullable(JsonNullable<Object> seed) {
    this.seed = seed;
  }

  public void setSeed(Object seed) {
    this.seed = JsonNullable.<Object>of(seed);
  }


  public DreamboothInpaintingRequest strength(BigDecimal strength) {
    
    this.strength = strength;
    return this;
  }

   /**
   * Get strength
   * @return strength
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getStrength() {
    return strength;
  }


  @JsonProperty(JSON_PROPERTY_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrength(BigDecimal strength) {
    this.strength = strength;
  }


  public DreamboothInpaintingRequest tomesd(String tomesd) {
    
    this.tomesd = tomesd;
    return this;
  }

   /**
   * Get tomesd
   * @return tomesd
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOMESD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTomesd() {
    return tomesd;
  }


  @JsonProperty(JSON_PROPERTY_TOMESD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTomesd(String tomesd) {
    this.tomesd = tomesd;
  }


  public DreamboothInpaintingRequest trackId(Object trackId) {
    this.trackId = JsonNullable.<Object>of(trackId);
    
    return this;
  }

   /**
   * Get trackId
   * @return trackId
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getTrackId() {
        return trackId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getTrackId_JsonNullable() {
    return trackId;
  }
  
  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  public void setTrackId_JsonNullable(JsonNullable<Object> trackId) {
    this.trackId = trackId;
  }

  public void setTrackId(Object trackId) {
    this.trackId = JsonNullable.<Object>of(trackId);
  }


  public DreamboothInpaintingRequest useKarrasSigmas(String useKarrasSigmas) {
    
    this.useKarrasSigmas = useKarrasSigmas;
    return this;
  }

   /**
   * Get useKarrasSigmas
   * @return useKarrasSigmas
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USE_KARRAS_SIGMAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUseKarrasSigmas() {
    return useKarrasSigmas;
  }


  @JsonProperty(JSON_PROPERTY_USE_KARRAS_SIGMAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseKarrasSigmas(String useKarrasSigmas) {
    this.useKarrasSigmas = useKarrasSigmas;
  }


  public DreamboothInpaintingRequest vae(Object vae) {
    this.vae = JsonNullable.<Object>of(vae);
    
    return this;
  }

   /**
   * Get vae
   * @return vae
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getVae() {
        return vae.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VAE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getVae_JsonNullable() {
    return vae;
  }
  
  @JsonProperty(JSON_PROPERTY_VAE)
  public void setVae_JsonNullable(JsonNullable<Object> vae) {
    this.vae = vae;
  }

  public void setVae(Object vae) {
    this.vae = JsonNullable.<Object>of(vae);
  }


  public DreamboothInpaintingRequest webhook(Object webhook) {
    this.webhook = JsonNullable.<Object>of(webhook);
    
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Object getWebhook() {
        return webhook.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WEBHOOK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getWebhook_JsonNullable() {
    return webhook;
  }
  
  @JsonProperty(JSON_PROPERTY_WEBHOOK)
  public void setWebhook_JsonNullable(JsonNullable<Object> webhook) {
    this.webhook = webhook;
  }

  public void setWebhook(Object webhook) {
    this.webhook = JsonNullable.<Object>of(webhook);
  }


  public DreamboothInpaintingRequest width(String width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(String width) {
    this.width = width;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DreamboothInpaintingRequest dreamboothInpaintingRequest = (DreamboothInpaintingRequest) o;
    return equalsNullable(this.embeddingsModel, dreamboothInpaintingRequest.embeddingsModel) &&
        Objects.equals(this.enhancePrompt, dreamboothInpaintingRequest.enhancePrompt) &&
        Objects.equals(this.guidanceScale, dreamboothInpaintingRequest.guidanceScale) &&
        Objects.equals(this.height, dreamboothInpaintingRequest.height) &&
        Objects.equals(this.initImage, dreamboothInpaintingRequest.initImage) &&
        Objects.equals(this.key, dreamboothInpaintingRequest.key) &&
        equalsNullable(this.loraModel, dreamboothInpaintingRequest.loraModel) &&
        equalsNullable(this.loraStrength, dreamboothInpaintingRequest.loraStrength) &&
        Objects.equals(this.maskImage, dreamboothInpaintingRequest.maskImage) &&
        Objects.equals(this.modelId, dreamboothInpaintingRequest.modelId) &&
        equalsNullable(this.negativePrompt, dreamboothInpaintingRequest.negativePrompt) &&
        Objects.equals(this.numInferenceSteps, dreamboothInpaintingRequest.numInferenceSteps) &&
        Objects.equals(this.prompt, dreamboothInpaintingRequest.prompt) &&
        Objects.equals(this.safetyChecker, dreamboothInpaintingRequest.safetyChecker) &&
        Objects.equals(this.samples, dreamboothInpaintingRequest.samples) &&
        equalsNullable(this.scheduler, dreamboothInpaintingRequest.scheduler) &&
        equalsNullable(this.seed, dreamboothInpaintingRequest.seed) &&
        Objects.equals(this.strength, dreamboothInpaintingRequest.strength) &&
        Objects.equals(this.tomesd, dreamboothInpaintingRequest.tomesd) &&
        equalsNullable(this.trackId, dreamboothInpaintingRequest.trackId) &&
        Objects.equals(this.useKarrasSigmas, dreamboothInpaintingRequest.useKarrasSigmas) &&
        equalsNullable(this.vae, dreamboothInpaintingRequest.vae) &&
        equalsNullable(this.webhook, dreamboothInpaintingRequest.webhook) &&
        Objects.equals(this.width, dreamboothInpaintingRequest.width);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(embeddingsModel), enhancePrompt, guidanceScale, height, initImage, key, hashCodeNullable(loraModel), hashCodeNullable(loraStrength), maskImage, modelId, hashCodeNullable(negativePrompt), numInferenceSteps, prompt, safetyChecker, samples, hashCodeNullable(scheduler), hashCodeNullable(seed), strength, tomesd, hashCodeNullable(trackId), useKarrasSigmas, hashCodeNullable(vae), hashCodeNullable(webhook), width);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DreamboothInpaintingRequest {\n");
    sb.append("    embeddingsModel: ").append(toIndentedString(embeddingsModel)).append("\n");
    sb.append("    enhancePrompt: ").append(toIndentedString(enhancePrompt)).append("\n");
    sb.append("    guidanceScale: ").append(toIndentedString(guidanceScale)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    initImage: ").append(toIndentedString(initImage)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    loraModel: ").append(toIndentedString(loraModel)).append("\n");
    sb.append("    loraStrength: ").append(toIndentedString(loraStrength)).append("\n");
    sb.append("    maskImage: ").append(toIndentedString(maskImage)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    negativePrompt: ").append(toIndentedString(negativePrompt)).append("\n");
    sb.append("    numInferenceSteps: ").append(toIndentedString(numInferenceSteps)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    safetyChecker: ").append(toIndentedString(safetyChecker)).append("\n");
    sb.append("    samples: ").append(toIndentedString(samples)).append("\n");
    sb.append("    scheduler: ").append(toIndentedString(scheduler)).append("\n");
    sb.append("    seed: ").append(toIndentedString(seed)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("    tomesd: ").append(toIndentedString(tomesd)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("    useKarrasSigmas: ").append(toIndentedString(useKarrasSigmas)).append("\n");
    sb.append("    vae: ").append(toIndentedString(vae)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `embeddings_model` to the URL query string
    if (getEmbeddingsModel() != null) {
      try {
        joiner.add(String.format("%sembeddings_model%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEmbeddingsModel()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `enhance_prompt` to the URL query string
    if (getEnhancePrompt() != null) {
      try {
        joiner.add(String.format("%senhance_prompt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEnhancePrompt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `guidance_scale` to the URL query string
    if (getGuidanceScale() != null) {
      try {
        joiner.add(String.format("%sguidance_scale%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getGuidanceScale()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `height` to the URL query string
    if (getHeight() != null) {
      try {
        joiner.add(String.format("%sheight%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHeight()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `init_image` to the URL query string
    if (getInitImage() != null) {
      try {
        joiner.add(String.format("%sinit_image%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInitImage()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      try {
        joiner.add(String.format("%skey%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getKey()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lora_model` to the URL query string
    if (getLoraModel() != null) {
      try {
        joiner.add(String.format("%slora_model%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLoraModel()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lora_strength` to the URL query string
    if (getLoraStrength() != null) {
      try {
        joiner.add(String.format("%slora_strength%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLoraStrength()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mask_image` to the URL query string
    if (getMaskImage() != null) {
      try {
        joiner.add(String.format("%smask_image%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaskImage()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `model_id` to the URL query string
    if (getModelId() != null) {
      try {
        joiner.add(String.format("%smodel_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getModelId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `negative_prompt` to the URL query string
    if (getNegativePrompt() != null) {
      try {
        joiner.add(String.format("%snegative_prompt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNegativePrompt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `num_inference_steps` to the URL query string
    if (getNumInferenceSteps() != null) {
      try {
        joiner.add(String.format("%snum_inference_steps%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNumInferenceSteps()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `prompt` to the URL query string
    if (getPrompt() != null) {
      try {
        joiner.add(String.format("%sprompt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrompt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `safety_checker` to the URL query string
    if (getSafetyChecker() != null) {
      try {
        joiner.add(String.format("%ssafety_checker%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSafetyChecker()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `samples` to the URL query string
    if (getSamples() != null) {
      try {
        joiner.add(String.format("%ssamples%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSamples()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `scheduler` to the URL query string
    if (getScheduler() != null) {
      try {
        joiner.add(String.format("%sscheduler%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScheduler()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `seed` to the URL query string
    if (getSeed() != null) {
      try {
        joiner.add(String.format("%sseed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSeed()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `strength` to the URL query string
    if (getStrength() != null) {
      try {
        joiner.add(String.format("%sstrength%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStrength()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tomesd` to the URL query string
    if (getTomesd() != null) {
      try {
        joiner.add(String.format("%stomesd%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTomesd()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `track_id` to the URL query string
    if (getTrackId() != null) {
      try {
        joiner.add(String.format("%strack_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTrackId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `use_karras_sigmas` to the URL query string
    if (getUseKarrasSigmas() != null) {
      try {
        joiner.add(String.format("%suse_karras_sigmas%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUseKarrasSigmas()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vae` to the URL query string
    if (getVae() != null) {
      try {
        joiner.add(String.format("%svae%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVae()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `webhook` to the URL query string
    if (getWebhook() != null) {
      try {
        joiner.add(String.format("%swebhook%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWebhook()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `width` to the URL query string
    if (getWidth() != null) {
      try {
        joiner.add(String.format("%swidth%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWidth()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

