/*
 * ModelsLab AI API's
 * This is ModelsLab Stable Diffusion and Multiple AI APIs, here you can pass details to generate images using API, without needs of GPU locally.  You will need to have _**api key**_ to generate images, if you don't have it, get it from [https://modelslab.com](https://modelslab.com/)  Send Json post request with data and links, don't send files as raw format, send accessible links instead
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.modelslab;

import com.simiacryptus.api.java.ApiException;
import com.simiacryptus.api.java.modelslab.model.CreateDreamboothRequest200Response;
import com.simiacryptus.api.java.modelslab.model.CreateDreamboothRequestRequest;
import com.simiacryptus.api.java.modelslab.model.FetchQueuedImagesRequest;
import com.simiacryptus.api.java.modelslab.model.GetTrainingStatus200Response;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrainModelSandboxApiApi
 */
@Ignore
public class TrainModelSandboxApiApiTest {

    private final TrainModelSandboxApiApi api = new TrainModelSandboxApiApi();

    /**
     * Create Dreambooth Request
     *
     * Create Dreambooth Request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDreamboothRequest1Test() throws ApiException {
        CreateDreamboothRequestRequest createDreamboothRequestRequest = null;
        CreateDreamboothRequest200Response response = api.createDreamboothRequest1(createDreamboothRequestRequest);

        // TODO: test validations
    }
    /**
     * Get Training Status
     *
     * Get Training Status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTrainingStatus1Test() throws ApiException {
        FetchQueuedImagesRequest fetchQueuedImagesRequest = null;
        GetTrainingStatus200Response response = api.getTrainingStatus1(fetchQueuedImagesRequest);

        // TODO: test validations
    }
}
