/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ChatCompletionTokenLogprobTopLogprobsInner
 */
public class ChatCompletionTokenLogprobTopLogprobsInnerTest {
    private final ChatCompletionTokenLogprobTopLogprobsInner model = new ChatCompletionTokenLogprobTopLogprobsInner();

    /**
     * Model tests for ChatCompletionTokenLogprobTopLogprobsInner
     */
    @Test
    public void testChatCompletionTokenLogprobTopLogprobsInner() {
        // TODO: test ChatCompletionTokenLogprobTopLogprobsInner
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'logprob'
     */
    @Test
    public void logprobTest() {
        // TODO: test logprob
    }

    /**
     * Test the property 'bytes'
     */
    @Test
    public void bytesTest() {
        // TODO: test bytes
    }

}
