/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ChatCompletionRequestMessageContentPartImageImageUrl
 */
public class ChatCompletionRequestMessageContentPartImageImageUrlTest {
    private final ChatCompletionRequestMessageContentPartImageImageUrl model = new ChatCompletionRequestMessageContentPartImageImageUrl();

    /**
     * Model tests for ChatCompletionRequestMessageContentPartImageImageUrl
     */
    @Test
    public void testChatCompletionRequestMessageContentPartImageImageUrl() {
        // TODO: test ChatCompletionRequestMessageContentPartImageImageUrl
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

}
