/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.simiacryptus.api.java.openai.model.CreateModerationResponseResultsInnerCategories;
import com.simiacryptus.api.java.openai.model.CreateModerationResponseResultsInnerCategoryScores;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateModerationResponseResultsInner
 */
public class CreateModerationResponseResultsInnerTest {
    private final CreateModerationResponseResultsInner model = new CreateModerationResponseResultsInner();

    /**
     * Model tests for CreateModerationResponseResultsInner
     */
    @Test
    public void testCreateModerationResponseResultsInner() {
        // TODO: test CreateModerationResponseResultsInner
    }

    /**
     * Test the property 'flagged'
     */
    @Test
    public void flaggedTest() {
        // TODO: test flagged
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'categoryScores'
     */
    @Test
    public void categoryScoresTest() {
        // TODO: test categoryScores
    }

}
