/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.simiacryptus.api.java.openai.model.CreateFineTuningJobRequestHyperparameters;
import com.simiacryptus.api.java.openai.model.CreateFineTuningJobRequestModel;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateFineTuningJobRequest
 */
public class CreateFineTuningJobRequestTest {
    private final CreateFineTuningJobRequest model = new CreateFineTuningJobRequest();

    /**
     * Model tests for CreateFineTuningJobRequest
     */
    @Test
    public void testCreateFineTuningJobRequest() {
        // TODO: test CreateFineTuningJobRequest
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'trainingFile'
     */
    @Test
    public void trainingFileTest() {
        // TODO: test trainingFile
    }

    /**
     * Test the property 'hyperparameters'
     */
    @Test
    public void hyperparametersTest() {
        // TODO: test hyperparameters
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'validationFile'
     */
    @Test
    public void validationFileTest() {
        // TODO: test validationFile
    }

}
