/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateImageEditRequestModel
 */
public class CreateImageEditRequestModelTest {
    private final CreateImageEditRequestModel model = new CreateImageEditRequestModel();

    /**
     * Model tests for CreateImageEditRequestModel
     */
    @Test
    public void testCreateImageEditRequestModel() {
        // TODO: test CreateImageEditRequestModel
    }

}
