/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Image
 */
public class ImageTest {
    private final Image model = new Image();

    /**
     * Model tests for Image
     */
    @Test
    public void testImage() {
        // TODO: test Image
    }

    /**
     * Test the property 'b64Json'
     */
    @Test
    public void b64JsonTest() {
        // TODO: test b64Json
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'revisedPrompt'
     */
    @Test
    public void revisedPromptTest() {
        // TODO: test revisedPrompt
    }

}
