/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for MessageContentTextAnnotationsFileCitationObjectFileCitation
 */
public class MessageContentTextAnnotationsFileCitationObjectFileCitationTest {
    private final MessageContentTextAnnotationsFileCitationObjectFileCitation model = new MessageContentTextAnnotationsFileCitationObjectFileCitation();

    /**
     * Model tests for MessageContentTextAnnotationsFileCitationObjectFileCitation
     */
    @Test
    public void testMessageContentTextAnnotationsFileCitationObjectFileCitation() {
        // TODO: test MessageContentTextAnnotationsFileCitationObjectFileCitation
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'quote'
     */
    @Test
    public void quoteTest() {
        // TODO: test quote
    }

}
