/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.simiacryptus.api.java.openai.model.AssistantObjectToolsInner;
import com.simiacryptus.api.java.openai.model.RunCompletionUsage;
import com.simiacryptus.api.java.openai.model.RunObjectLastError;
import com.simiacryptus.api.java.openai.model.RunObjectRequiredAction;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RunObject
 */
public class RunObjectTest {
    private final RunObject model = new RunObject();

    /**
     * Model tests for RunObject
     */
    @Test
    public void testRunObject() {
        // TODO: test RunObject
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'threadId'
     */
    @Test
    public void threadIdTest() {
        // TODO: test threadId
    }

    /**
     * Test the property 'assistantId'
     */
    @Test
    public void assistantIdTest() {
        // TODO: test assistantId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'requiredAction'
     */
    @Test
    public void requiredActionTest() {
        // TODO: test requiredAction
    }

    /**
     * Test the property 'lastError'
     */
    @Test
    public void lastErrorTest() {
        // TODO: test lastError
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'cancelledAt'
     */
    @Test
    public void cancelledAtTest() {
        // TODO: test cancelledAt
    }

    /**
     * Test the property 'failedAt'
     */
    @Test
    public void failedAtTest() {
        // TODO: test failedAt
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    public void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'instructions'
     */
    @Test
    public void instructionsTest() {
        // TODO: test instructions
    }

    /**
     * Test the property 'tools'
     */
    @Test
    public void toolsTest() {
        // TODO: test tools
    }

    /**
     * Test the property 'fileIds'
     */
    @Test
    public void fileIdsTest() {
        // TODO: test fileIds
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

}
