/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.simiacryptus.api.java.openai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.simiacryptus.api.java.openai.model.RunStepDetailsToolCallsObjectToolCallsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RunStepDetailsToolCallsObject
 */
public class RunStepDetailsToolCallsObjectTest {
    private final RunStepDetailsToolCallsObject model = new RunStepDetailsToolCallsObject();

    /**
     * Model tests for RunStepDetailsToolCallsObject
     */
    @Test
    public void testRunStepDetailsToolCallsObject() {
        // TODO: test RunStepDetailsToolCallsObject
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'toolCalls'
     */
    @Test
    public void toolCallsTest() {
        // TODO: test toolCalls
    }

}
